version: "3.8"
services:
  stubby:
    image: d6cb6d73h/stubby:1.3
    ports:
      - published: 8053
        target: 53
        protocol: udp
      - published: 8053
        target: 53
        protocol: tcp
    command:
      # - "-l"
